#!/bin/bash
cd llvm/tools
svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
cd ../..

cd llvm/tools/clang/tools
svn co http://llvm.org/svn/llvm-project/clang-tools-extra/trunk extra
cd ../../../..

cd llvm/projects
svn co http://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt
cd ../..

mkdir build
cd build
#../llvm/configure CC=/usr/bin/clang CXX=/usr/bin/clang++ --disable-compiler-version-checks
CC=gcc CXX=g++ ../llvm/configure --enable-optimized
make -j4

