#!/bin/bash
wget "http://community.topcoder.com/tc?module=ProblemArchive&sr=1&er=3256&sc=&sd=&class=&cat=&div1l=&div2l=&mind1s=&mind2s=&maxd1s=&maxd2s=&wr=" --output-document=list.html
grep -o 'pm=[0-9]*' list.html >tmp.txt
sed -i 's/pm=//' tmp.txt
cat tmp.txt | sort -u > list.txt
echo "finish generate problem id"
if which gettc; then
    echo "gettc installed."
else
    echo "No gettc installed, installing gettc"
    git clone https://github.com/seri/gettc.git
    pushd gettc
    rake
    popd
    gem install gettc
    rm -rf gettc
fi

mkdir _prob
popd _prob
for num in `cat ../list.txt`; do gettc $num; done
popd
echo "Finish download everthing"

echo "Begin to make ebook"
mkdir _ebook
for dir in `ls _prob`; do mkdir _ebook/$dir; cp -a _prob/$dir/prob _ebook/$dir/; done
pushd _ebook
rm -rf _ebook
rm */*/*.md
echo "<html><body><h1>Table of Contents</h1>" > index.html
echo "<ul>" >> index.html
find . | grep html | sort > tmplist.txt
for file in `cat tmplist.txt`; do
  name=`echo $file | awk -F/ '{print $2}'`
  echo "<li><a href=\"$file\">$name</a></li>" >> index.html
done
echo "</ul>" >> index.html
echo "</body></html>" >> index.html
rm tmplist.txt
popd
zip -r _EBOOK.zip _ebook
echo "Done!!"
