#!/usr/bin/sh

if [ $# -eq 1 ]; then
    if [[ $1 = "git" ]]; then
        GIT=1
    elif [[ $1 = "svn" ]]; then
        SVN=1
    else
        echo "git only update git repositories"
        echo "svn only update svn repositories"
        echo "--help for help"
        exit
    fi
fi
    
for dir in `ls`; do
   if [ -d "$dir" ]; then
       pushd "$dir"
       pwd
       if [ -d opencv ]; then
           OPENCV=1
           pushd opencv
       else
           OPENCV=0
       fi
       if [ -d .git ] && ( ( [ ! -z $GIT ] && [ -z $SVN ] ) || ( [ -z $SVN ] && [ -z $GIT ] ) ); then
           git reset --hard
           git pull
       fi
       if [ -d .svn ] && ( ( [ ! -z $SVN ] && [ -z $GIT ] ) || ( [ -z $SVN ] && [ -z $GIT ] ) ); then
           svn cleanup
           svn upgrade .
           svn update .
       fi
       if [ -d .hg ]; then
          hg pull
          hg update
       fi
       if [ $OPENCV -eq 1 ]; then
           popd
       fi
       popd
   fi
done
