#!/usr/bin/sh
for dir in `ls`; do
   if [ -d "$dir" ]; then
       pushd "$dir"
       pwd
       if [ -d .git ]; then
           git reset --hard
           git pull
       fi
       if [ -d .svn ]; then
           svn cleanup
           svn upgrade .
           svn update .
       fi
       popd
   fi
done
